spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exchangedatadev
    username: postgres
    password: postgres
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.r2dbc: INFO
    org.springframework: INFO
