spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exchangedatadev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

jwt:
  private-key: classpath:jwt/app.key
  public-key: classpath:jwt/app.pub
  ttl: 60m
  refresh-token-ttl: 1d

logging:
  level:
    org.springframework.r2dbc: INFO
    org.springframework: INFO
