spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exchangedatadev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.springframework.r2dbc: INFO
    org.springframework: INFO
