/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainImport } from './routes/main'
import { Route as TradeIndexImport } from './routes/trade/index'
import { Route as TradeIdIndexImport } from './routes/trade/$id/index'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const MainRoute = MainImport.update({
  path: '/main',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const TradeIndexRoute = TradeIndexImport.update({
  path: '/trade/',
  getParentRoute: () => rootRoute,
} as any)

const TradeIdIndexRoute = TradeIdIndexImport.update({
  path: '/trade/$id/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/trade/': {
      id: '/trade/'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeIndexImport
      parentRoute: typeof rootRoute
    }
    '/trade/$id/': {
      id: '/trade/$id/'
      path: '/trade/$id'
      fullPath: '/trade/$id'
      preLoaderRoute: typeof TradeIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/main': typeof MainRoute
  '/about': typeof AboutLazyRoute
  '/trade': typeof TradeIndexRoute
  '/trade/$id': typeof TradeIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/main': typeof MainRoute
  '/about': typeof AboutLazyRoute
  '/trade': typeof TradeIndexRoute
  '/trade/$id': typeof TradeIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/main': typeof MainRoute
  '/about': typeof AboutLazyRoute
  '/trade/': typeof TradeIndexRoute
  '/trade/$id/': typeof TradeIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/main' | '/about' | '/trade' | '/trade/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/main' | '/about' | '/trade' | '/trade/$id'
  id: '__root__' | '/' | '/main' | '/about' | '/trade/' | '/trade/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  MainRoute: typeof MainRoute
  AboutLazyRoute: typeof AboutLazyRoute
  TradeIndexRoute: typeof TradeIndexRoute
  TradeIdIndexRoute: typeof TradeIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  MainRoute: MainRoute,
  AboutLazyRoute: AboutLazyRoute,
  TradeIndexRoute: TradeIndexRoute,
  TradeIdIndexRoute: TradeIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/main",
        "/about",
        "/trade/",
        "/trade/$id/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/main": {
      "filePath": "main.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/trade/": {
      "filePath": "trade/index.tsx"
    },
    "/trade/$id/": {
      "filePath": "trade/$id/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
