/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthTradeIndexImport } from './routes/_auth/trade/index'
import { Route as AuthDashboardIndexImport } from './routes/_auth/dashboard/index'
import { Route as AuthTradeIdIndexImport } from './routes/_auth/trade/$id/index'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthTradeIndexRoute = AuthTradeIndexImport.update({
  path: '/trade/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthDashboardIndexRoute = AuthDashboardIndexImport.update({
  path: '/dashboard/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthTradeIdIndexRoute = AuthTradeIdIndexImport.update({
  path: '/trade/$id/',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/trade/': {
      id: '/_auth/trade/'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof AuthTradeIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/trade/$id/': {
      id: '/_auth/trade/$id/'
      path: '/trade/$id'
      fullPath: '/trade/$id'
      preLoaderRoute: typeof AuthTradeIdIndexImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
  AuthTradeIndexRoute: typeof AuthTradeIndexRoute
  AuthTradeIdIndexRoute: typeof AuthTradeIdIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
  AuthTradeIndexRoute: AuthTradeIndexRoute,
  AuthTradeIdIndexRoute: AuthTradeIdIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/trade': typeof AuthTradeIndexRoute
  '/trade/$id': typeof AuthTradeIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/trade': typeof AuthTradeIndexRoute
  '/trade/$id': typeof AuthTradeIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
  '/_auth/trade/': typeof AuthTradeIndexRoute
  '/_auth/trade/$id/': typeof AuthTradeIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/login' | '/dashboard' | '/trade' | '/trade/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/login' | '/dashboard' | '/trade' | '/trade/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/dashboard/'
    | '/_auth/trade/'
    | '/_auth/trade/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/dashboard/",
        "/_auth/trade/",
        "/_auth/trade/$id/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_auth/dashboard/": {
      "filePath": "_auth/dashboard/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/trade/": {
      "filePath": "_auth/trade/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/trade/$id/": {
      "filePath": "_auth/trade/$id/index.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
